# Auto-generated by bootstrap.sh
# Do not edit bucket/table/region manually — re-run bootstrap.sh instead

terraform {
  backend "s3" {
    bucket         = "payflow-tfstate-470439679607"
    key            = "aws/bastion/terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "payflow-tfstate-lock"
    encrypt        = true
  }
}
