apiVersion: v1
kind: ResourceQuota
metadata:
  name: payflow-quota
  namespace: payflow
  labels:
    {{- include "payflow.labels" . | nindent 4 }}
spec:
  hard:
    requests.cpu: "3"
    requests.memory: 3Gi
    limits.cpu: "6"
    limits.memory: 6Gi
    pods: "30"
