apiVersion: v1
kind: ResourceQuota
metadata:
  name: payflow-quota
  namespace: payflow
  labels:
    {{- include "payflow.labels" . | nindent 4 }}
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 8Gi
    pods: "30"
